version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      # - node.name=es-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  filebeat:
    build: ./filebeat
    user: root
    depends_on:
      - logstash
    volumes:
      - ./express-app/logs:/var/log/express
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # - /var/run/docker.sock:/var/run/docker.sock:ro

  app1:
    build: ./app1
    container_name: app1
    volumes:
      - ./express-app/logs:/app/logs
    environment:
      - APP_NAME=App1
    ports:
      - "3001:3000"

  app2:
    build: ./app2
    container_name: app2
    volumes:
      - ./express-app/logs:/app/logs
    environment:
      - APP_NAME=App2
    ports:
      - "3002:3000"
